### PR TITLE
Add a copy button

### LINKED ISSUE #34: Copy to Clipboard Button
Having one for the installation section would be good.
I personally like the style in https://brew.sh but, yes it can be anything.

### PR DESCRIPTION
**Pull request by naveen521kk**
fixes #34

### CODE REVIEW

**Comment by lazka** [comment]
```
> npm run build 
index.js → ../app/static/index.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
popper.js (imported by node_modules/bootstrap/dist/js/bootstrap.esm.js)
[!] (plugin postcss) Error: ".copyable button" failed to @extend ".rounded-end".
The selector ".rounded-end" was not found.
Use "@extend .rounded-end !optional" if the extend should be able to fail.
style.scss
Error: ".copyable button" failed to @extend ".rounded-end".
The selector ".rounded-end" was not found.
Use "@extend .rounded-end !optional" if the extend should be able to fail.
    at options.error (/home/lazka/Desktop/git/msys2-web/frontend/node_modules/node-sass/lib/index.js:290:33)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `rollup --config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lazka/.npm/_logs/2021-01-15T12_25_17_711Z-debug.log
```

**Comment by naveen521kk** [comment]
I didn't commit the `package.json` nor `package-lock.json` because my npm is super old one, at least it didn't parse the lock file itself.

Updating bootstrap to `v5.0.0-beta1` will fix this :)

**Comment by naveen521kk** [comment]
> I didn't commit the package.json nor package-lock.json because my npm is super old one, at least it didn't parse the lock file itself.

If it's ok, I will commit, I think it should be backwards compatible, but don't know.

**Comment by naveen521kk** [comment]
please squash while merging

**Pull request merged**
